# config.yaml
# CUDA_VISIBLE_DEVICES=2 python test.py --dataroot /media/NAS07/USER_PATH/peiyuan/paired/images/T1 
#--name utrans_utrans_fth025_depth12_nld3_ssi0 --model utrans --results_dir /media/NAS07/USER_PATH/peiyuan/PGD/Comparison/transunet_output --phase test 
#--epoch latest --checkpoints_dir /media/NAS07/USER_PATH/peiyuan/PGD/Comparison/transunet --netG=utrans --dataset_mode aligned --load_size=224 --preprocess resize

# ==== Common training settings ====
dataroot: "/media/NAS07/USER_PATH/peiyuan/paired_KCL/images/HFC"
name: "pss_lsc_sgp_unest_fth025_depth12_nld3_ssi0"
checkpoints_dir: "/media/NAS07/USER_PATH/peiyuan/PGD/pss_lsc_sgp/"
gpu_ids: "1"
results_dir: /media/NAS_R02/USER_PATH/Zhenxuan/TMI_LFHF/PGD/pss/comparison_KCL/HFC/pss_lsc_sgp_result
epoch: best
# ==== Model & Dataset ====
model: "pss"
netG: "unest"
dataset_mode: "aligned"
input_nc: 1
output_nc: 1

# ==== Training settings ====
phase: "test"
lambda_L1: 100.0
batch_size: 1
load_size: 224
preprocess: "resize"
n_epochs: 10
n_epochs_decay: 10
save_epoch_freq: 1
continue_train: true
# ==== Display ====
display_id: -1

# ==== PSS_DIFF Settings ====
PSS:
  path: None
  image_size: 224
  model:
    type: "simple"
    in_channels: 2
    out_ch: 1
    ch: 128
    ch_mult: [1, 2, 2, 2, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True
    resamp_with_conv: True

  diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 100

  training:
    batch_size: 128
    n_epochs: 10000
    n_iters: 5000000
    snapshot_freq: 5000
    validation_freq: 20000

  sampling:
    batch_size: 32
    last_only: True

  optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0004
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0
# ==== Logging / Output ====
# If you want to redirect stdout/stderr to a log file like in your bash command,
# do that in your shell script, not in YAML.
# train: 
#screen -dmS training_session bash -c 'python pss_train.py --config train_configs/t1_pair_train_pss.yaml > /home/zhangzx/PSS-Diff/train_logs/t1_pair_pss.log 2>&1'

# python test.py \
#   --config ./test_configs/t1_test_pss_lsc_sgp.yaml \
#   --dataroot /media/NAS07/USER_PATH/peiyuan/paired_KCL/images/HFC \
#   --name pss_sgp_unest_fth025_depth12_nld3_ssi0 \
#   --checkpoints_dir /media/NAS07/USER_PATH/peiyuan/PGD/pss_lsc_sgp \
#   --results_dir /media/NAS_R02/USER_PATH/Zhenxuan/TMI_LFHF/PGD/pss/comparison_KCL/HFC/pss_sgp_result \
#   --model pss \
#   --netG unest \
#   --dataset_mode aligned \
#   --input_nc 1 \
#   --output_nc 1 \
#   --epoch best \
#   --phase test \
#   --gpu_ids 1 \
#   --no_flip
